-- Drunk Command
RegisterCommand("drunk", function(source, args)
    alert("~g~You just drank some booze")
    TaskStartScenarioInPlace(player, "WORLD_HUMAN_DRINKING", 0, 1) 
    SetPedMotionBlur(player, true)
    AnimpostfxPlay ("DrugsMichaelAliensFight", 10000001, true)
    SetPedIsDrunk(player, true)
    SetPedMovementClipset(player, "MOVE_M@DRUNK@VERYDRUNK", true)
    ShakeGameplayCam("DRUNK_SHAKE", 1.0)
end)

RegisterCommand("resetdrunk", function(source, args)
    SetPedIsDrunk(GetPlayerPed(-1), false)		
    SetPedMotionBlur(playerPed, false)
   ResetPedMovementClipset(GetPlayerPed(-1))
   AnimpostfxStopAll()
   SetPedMovementClipset(player, "MOVE_M@DRUNK@VERYDRUNK", false)
    ShakeGameplayCam("DRUNK_SHAKE", 0.0) 
end)